=== anubias7/MXM2NQ_XMLgyak/MXM2NQ_10_20/macskakMXM2NQ.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="cats">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="cat" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="name" type="xs:string"></xs:element>
                            <xs:element name="age" type="xs:decimal"></xs:element>
                            <xs:element name="breed" type="xs:string"></xs:element>
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:ID" use="required"></xs:attribute>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== anubias7/MXM2NQ_XMLgyak/MXM2NQ_10_20/macskakMXM2NQ.xml
<?xml version="1.0" encoding="utf-8"?>
<cats xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="macskakMXM2NQ.xsd">
    <!--<!DOCTYPE cats SYSTEM "macskakMXM2NQ.dtd">
    <cats> -->
    <cat id="c-1">
        <name>Macsek</name>
        <age>5</age>
        <breed>Brit rövidszőrű</breed>
    </cat>
    <cat id="c-2">
        <name>Kandúr</name>
        <age>1.5</age>
        <breed>Keverék</breed>
    </cat>
    <cat id="c-3">
        <name>Foltos</name>
        <age>3</age>
        <breed>Házi macska</breed>
    </cat>
</cats>
