=== anubias7/MXM2NQ_XMLgyak/MXM2NQ_10_06/KM_orarend.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="lectures">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="lecture" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="subject" type="xs:string"></xs:element>
                            <xs:element name="date">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="day" type="xs:string"></xs:element>
                                        <xs:element name="start" type="xs:unsignedShort"></xs:element>
                                        <xs:element name="end" type="xs:unsignedShort"></xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="place" type="xs:string"></xs:element>
                            <xs:element name="teacher" type="xs:string"></xs:element>
                            <xs:element name="faculty" type="xs:string"></xs:element>
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:string" use="required"></xs:attribute>
                        <xs:attribute name="type" type="xs:string" use="required"></xs:attribute>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== anubias7/MXM2NQ_XMLgyak/MXM2NQ_10_06/KM_orarend.xml
<?xml version="1.0" encoding="utf-8"?>

<lectures xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="KM_orarend.xsd">
    <lecture id="xmle" type="lecture">
        <subject> Adatkezelés XML-ben </subject>
        <date>
            <day> kedd </day>
            <start> 1200 </start>
            <end> 1400 </end>
        </date>
        <place> A2/I. előadó </place>
        <teacher> Dr. Bednarik László </teacher>
        <faculty> PTI </faculty>
    </lecture>

    <lecture id="xmlgy" type="practice">
        <subject> Adatkezelés XML-ben </subject>
        <date>
            <day> szerda </day>
            <start> 1000 </start>
            <end> 1200 </end>
        </date>
        <place> In/202 </place>
        <teacher> Dr. Bednarik László </teacher>
        <faculty> PTI </faculty>
    </lecture>

    <lecture id="vallalati" type="practice">
        <subject> Vállalati és pénzügyi rendszerek </subject>
        <date>
            <day> szerda </day>
            <start> 1600 </start>
            <end> 2000 </end>
        </date>
        <place> In/103 </place>
        <teacher> Dr. Sasvári Péter </teacher>
        <faculty> PTI </faculty>
    </lecture>
</lectures>
